apiVersion: v1
kind: LimitRange
metadata:
 name: limitrange-testing
spec:
 limits:
 - type: Pod
   min:
    cpu: 10m
    memory: 5Mi
   max:
    cpu: 500m
    memory: 300Mi
 - type: Container
   default:
    cpu: 100m
   min:
    cpu: 10m
   max:
    cpu: 500m